// Generated by CoffeeScript 2.5.1
(function() {
  var JSON_File, Package_File, copy, shade;

  ({copy, shade} = require('./lib/deep'));

  ({Package_File} = require('./lib/package_file'));

  ({JSON_File} = require('./lib/json_file'));

  exports.copy = copy;

  exports.shade = shade;

  exports.Package_File = Package_File;

  exports.JSON_File = JSON_File;

}).call(this);
