// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  var JSON_File, deep, fs, path;

  fs = require('fs');

  path = require('path');

  deep = require('./deep');

  JSON_File = class JSON_File {
    constructor(fname1) {
      this.save = this.save.bind(this);
      this.load = this.load.bind(this);
      this.load_json = this.load_json.bind(this);
      this.save_json = this.save_json.bind(this);
      this.apply_shadow = this.apply_shadow.bind(this);
      this.apply_shadow_file = this.apply_shadow_file.bind(this);
      this.fname = fname1;
      this.obj = {};
    }

    save() {
      return this.save_json(this.obj, this.fname);
    }

    load() {
      return this.obj = this.load_json(this.fname);
    }

    load_json(fname = this.fname) {
      var json, obj;
      if (fs.existsSync(fname)) {
        json = fs.readFileSync(fname, 'utf8');
        obj = JSON.parse(json);
      } else {
        obj = {};
      }
      return obj;
    }

    save_json(obj, fname) {
      var json;
      json = JSON.stringify(obj, null, 2);
      return fs.writeFileSync(fname, json);
    }

    apply_shadow(shadow_obj) {
      return this.obj = deep.shade(this.obj, shadow_obj);
    }

    apply_shadow_file(fname) {
      var obj;
      obj = this.load_json(fname);
      return this.apply_shadow(obj);
    }

  };

  exports.JSON_File = JSON_File;

}).call(this);
